# Generated by Django 3.0.3 on 2020-04-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertypewrapper',
            old_name='student',
            new_name='is_student',
        ),
    ]
