# Generated by Django 3.0.3 on 2020-04-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200409_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertypewrapper',
            old_name='is_student',
            new_name='is_lecturer',
        ),
    ]
