# Generated by Django 3.0.3 on 2020-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200409_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypewrapper',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
