# Generated by Django 3.0.3 on 2020-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('secret', models.CharField(max_length=64)),
            ],
        ),
    ]
