# Generated by Django 3.0.3 on 2020-03-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20200319_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('studentId', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='professorId',
            new_name='professor',
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Student')),
            ],
        ),
    ]
