# Generated by Django 3.0.3 on 2020-03-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20200319_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='moduleCode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.IntegerField(unique=True),
        ),
    ]
