# Generated by Django 3.0.3 on 2020-03-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20200328_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('student', 'module')},
        ),
    ]
