# Generated by Django 3.0.3 on 2020-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0013_attendance_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='deviceId',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
