# Generated by Django 3.0.3 on 2020-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0014_auto_20200423_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='deviceId',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
