# Generated by Django 3.0.3 on 2020-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0015_auto_20200423_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='moduleCode',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
