# Generated by Django 3.0.3 on 2020-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0016_auto_20200428_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
