# Generated by Django 3.0.3 on 2020-04-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0017_module_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='info',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='module',
            name='info',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
