# Generated by Django 3.0.3 on 2020-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0018_auto_20200428_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='info',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='module',
            name='info',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
