# Generated by Django 3.0.3 on 2020-05-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0019_auto_20200428_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='info',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='module',
            name='info',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
